# Generated by Django 3.1.7 on 2021-03-23 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='image',
            new_name='images',
        ),
    ]
