# Generated by Django 3.1.7 on 2021-03-24 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210324_1237'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
